# Generated by Django 5.2.14 on 2026-05-18 15:53

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codice')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('category', models.CharField(choices=[('QUALITY', 'Documento di qualità'), ('PROJECT', 'Documento di progetto')], max_length=20, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Responsabile')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='Numero revisione')),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('UNDER_REVIEW', 'In approvazione'), ('APPROVED', 'Approvato'), ('REJECTED', 'Rifiutato'), ('OBSOLETE', 'Obsoleto')], default='DRAFT', max_length=20, verbose_name='Stato')),
                ('change_summary', models.TextField(blank=True, verbose_name='Sommario modifiche')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Data efficacia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_versions', to=settings.AUTH_USER_MODEL, verbose_name='Autore')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Revisione documento',
                'verbose_name_plural': 'Revisioni documento',
                'ordering': ['document', '-created_at'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.document_file_upload_path, verbose_name='File')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome file originale')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dimensione (byte)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.documentversion', verbose_name='Revisione')),
            ],
            options={
                'verbose_name': 'File documento',
                'verbose_name_plural': 'File documenti',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
