# Generated by Django 5.2.14 on 2026-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_ecn_policy_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version_scheme',
            field=models.CharField(choices=[('numeric', 'Numerica'), ('alphabetic', 'Alfabetica')], default='numeric', help_text='Schema usato per le etichette di versione. Non modifica lo storico.', max_length=20, verbose_name='Schema versione'),
        ),
        migrations.AddField(
            model_name='document',
            name='versioning_mode',
            field=models.CharField(choices=[('revision_only', 'Solo revisione'), ('version_only', 'Solo versione'), ('both', 'Versione e revisione')], default='revision_only', help_text='Determina quali assi di versionamento usa questo documento.', max_length=20, verbose_name='Modalità versionamento'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='version_label',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Etichetta versione'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='version_number',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Numero versione'),
        ),
        migrations.AlterField(
            model_name='document',
            name='revision_scheme',
            field=models.CharField(choices=[('numeric', 'Numerica'), ('alphabetic', 'Alfabetica')], default='numeric', help_text='Schema usato per le etichette di revisione. Non modifica lo storico.', max_length=20, verbose_name='Schema revisione'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='revision_number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Numero revisione'),
        ),
    ]
