# Generated by Django 5.2.14 on 2026-05-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvato'), ('REJECTED', 'Rifiutato'), ('CANCELLED', 'Annullato')], default='PENDING', max_length=20, verbose_name='Stato')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='documents.documentversion', verbose_name='Revisione documento')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Richiesto da')),
            ],
            options={
                'verbose_name': 'Richiesta di approvazione',
                'verbose_name_plural': 'Richieste di approvazione',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approvato'), ('REJECTED', 'Rifiutato')], max_length=20, verbose_name='Decisione')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Approvatore')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='approvals.approvalrequest', verbose_name='Richiesta')),
            ],
            options={
                'verbose_name': 'Decisione di approvazione',
                'verbose_name_plural': 'Decisioni di approvazione',
                'ordering': ['-decided_at'],
                'unique_together': {('approval_request', 'approver')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequestApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notificato il')),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='approvals.approvalrequest', verbose_name='Richiesta')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Approvatore')),
            ],
            options={
                'verbose_name': 'Approvatore',
                'verbose_name_plural': 'Approvatori',
                'ordering': ['approval_request', 'order'],
                'unique_together': {('approval_request', 'approver')},
            },
        ),
    ]
